service: lambda-images

custom:
  BUCKET: 
  S3_ACCESS_KEY_ID: 
  S3_SECRET_ACCESS_KEY: 

provider:
  name: aws
  runtime: nodejs4.3
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:ListBucket
      Resource: "arn:aws:s3:::${self:custom.BUCKET}"
    - Effect: Allow
      Action:
        - s3:PutObject
        - s3:GetObject
        - s3:DeleteObject
      Resource: "arn:aws:s3:::${self:custom.BUCKET}/*"
      # -  Effect: "Allow"
      #   Action:
      #     - "s3:ListBucket"
      #   Resource:
      #     Fn::Join:
      #       - ""
      #       - - "arn:aws:s3:::"
      #         - Ref: ImageBucket
      # -  Effect: "Allow"
      #   Action:
      #     - "s3:PutObject"
      #   Resource:
      #     Fn::Join:
      #       - ""
      #       - - "arn:aws:s3:::"
      #         - Ref : "ImageBucket"

package:
 include:
   - ../node_modules/**

functions:
  upload:
    handler: handler.getSignedUrl
    environment:
      BUCKET: ${self:custom.BUCKET}
      S3_ACCESS_KEY_ID: ${self:custom.S3_ACCESS_KEY_ID}
      S3_SECRET_ACCESS_KEY: ${self:custom.S3_SECRET_ACCESS_KEY}

    events:
      - http:
          path: upload
          method: get
          cors: true
  public:
    handler: handler.publicEndpoint
    events:
      - http:
          path: public
          method: get
          cors: true
  private:
    handler: handler.privateEndpoint
    events:
      - http:
          path: private
          method: get
          authorizer: authFn
          cors: true
  authFn:
    handler: handler.auth


resources:
  Resources:
    TestBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:custom.BUCKET}
        AccessControl: Private

# resources:
#   Resources:
#     UsersDynamoDbTable:
#       Type: 'AWS::DynamoDB::Table'
#       Properties:
#         TableName: 'userz'
#         KeySchema:
#           - AttributeName: email
#             KeyType: HASH
#         AttributeDefinitions:
#           - AttributeName: email
#             AttributeType: S
#         ProvisionedThroughput:
#           ReadCapacityUnits: 1
#           WriteCapacityUnits: 1

